### ISSUE TITLE
Unintended outline present around tabs when using different color themes

### ISSUE THREAD

**Issue by Acumane** [wroyca/vscode-rounded#3]
### Adwaita theme:
![Screenshot from 2023-05-09 13-46-10](https://github.com/wroyca/libadwaita-vscode-theme/assets/94324138/67f66954-7bd4-493a-a228-80017e7b01ca)
### Dark default theme:
![Screenshot from 2023-05-09 13-45-51](https://github.com/wroyca/libadwaita-vscode-theme/assets/94324138/c4e59dba-a359-4eac-bfe4-61aae7c65b9a)

Especially visible on higher contrast themes:
![Screenshot from 2023-05-09 14-07-54](https://github.com/wroyca/libadwaita-vscode-theme/assets/94324138/c01b8d58-3232-42c0-bed9-ebe90f40544c)

Specifically, the **(1)** shouldn't be there, and **(2)** should wrap around the tab in a consistent stroke width

**Comment by wroyca** [comment]
Hi there, @Acumane! Can you kindly check if the problem mentioned exists with the [vscode-libadwaita-colorscheme](https://github.com/wroyca/libadwaita-vscode-theme/blob/main/vscode-libadwaita-colorscheme.json) provided in the repository? I have a feeling that this issue is particular to https://github.com/piousdeer/vscode-adwaita/issues/15.

**Comment by Acumane** [comment]
I will play around with piousdeer's colorscheme tonight, but the issue applies to any theme with outlines (the third image was taken with VSCode's "Dark High Contrast")

**Comment by wroyca** [comment]
> I will play around with piousdeer's colorscheme tonight, but the issue applies to any theme with outlines (the third image was taken with VSCode's "Dark High Contrast")


Ah, I understand now. It seems I overlooked the possibility of using a different color theme. Personally, I prefer to stick with the current theme provided in the repository and only make adjustments to the color scheme, rather than changing the entire color theme, when I want to achieve a different visual appearance. Thank you for bringing this to my attention!

**Comment by wroyca** [comment]
Hey @Acumane 

Unfortunately, the recent releases of Visual Studio Code have introduced two critical regressions: https://github.com/microsoft/vscode/issues/181805 and https://github.com/microsoft/vscode/issues/181805 respectively. I will need to postpone addressing this issue until a later time. It is possible that I will have to wait until a new version incorporating the latest Electron fixes is released before I can thoroughly investigate and resolve it

**Comment by wroyca** [comment]
Fixed with: https://github.com/wroyca/libadwaita-vscode-theme/commit/0f11f7622f4552d314e47b8103972a4b4958afd9

Note that I have not discovered a method to eliminate the background color from all tabs except for the active one. Interestingly, several themes employ a darker shade for the current tab and a lighter shade for the others, which contradicts the design principles of libadwaita and creates a somewhat awkward situation.

**Comment by Acumane** [comment]
Looks great!

> Interestingly, several themes employ a darker shade for the current tab and a lighter shade for the others, which contradicts the design principles of libadwaita

It's actually standard for active [Libadwaita tabs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.TabBar.html) to be darker and I'm not sure how I feel about it:
![tabs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/tab-bar.png)

I'm not too bothered by slightly unfaithful themes; between [Firefox](https://github.com/rafaelmardojai/firefox-gnome-theme), [Obsidian](https://github.com/birneee/obsidian-adwaita-theme), this theme, etc., complete consistency just isn't happening. To that end, I might look into adding a border around tabs for those higher contrast themes (so they're at least consistent w/ themselves). What do you think?

**Comment by wroyca** [comment]
> Looks great!
> 
> > Interestingly, several themes employ a darker shade for the current tab and a lighter shade for the others, which contradicts the design principles of libadwaita
> 
> It's actually standard for active [Libadwaita tabs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.TabBar.html) to be darker and I'm not sure how I feel about it: ![tabs](https://camo.githubusercontent.com/a29f0be7e02807ee834fd02066f8a2b4a3e9b52efa4ed1f9c2e62cb8f010e831/68747470733a2f2f676e6f6d652e70616765732e6769746c61622e676e6f6d652e6f72672f6c6962616477616974612f646f632f6d61696e2f7461622d6261722e706e67)
> 
> I'm not too bothered by slightly unfaithful themes; between [Firefox](https://github.com/rafaelmardojai/firefox-gnome-theme), [Obsidian](https://github.com/birneee/obsidian-adwaita-theme), this theme, etc., complete consistency just isn't happening. 

:sweat_smile: 

> To that end, I might look into adding a border around tabs for those higher contrast themes (so they're at least consistent w/ themselves). What do you think?

Absolutely! You're more than welcome to customize the theme according to your preferences. While I haven't provided detailed instructions for extensive customization, the theme is intentionally designed to be user-friendly and easily personalized. However, I will probably  not accept pull requests for customization changes - each person has their own unique perspectives in this regard, so I believe it's best for users to tweak their local copies based on their specific needs - our main focus should be ensuring the correctness of the theme's behavior so that we can strive for consistency as much as possible in a way that is painless to customize and integrate with existing color themes

**Comment by Acumane** [comment]
Edge case: the border returns when tabs start to wrap. I'll submit a PR later today

![Screenshot from 2023-05-12 12-51-09](https://github.com/wroyca/libadwaita-vscode-theme/assets/94324138/acc057bd-f6a9-4335-a82e-c33422d70737)
