### ISSUE TITLE
Feature request: tab bar visible only when 2+ editors are open

### ISSUE THREAD

**Issue by Acumane** [wroyca/vscode-rounded#5]
A hallmark of the Gnome tab bar is its disappearance when no/one tab is open. How difficult would it be to recreate this in VSCode (incl. animation)?

**Comment by wroyca** [comment]
I would absolutely love to see that in the future. It's definitely not an impossibly difficult task to accomplish, but I'm currently swamped with other commitments and I don't have the capacity to dive into it at the moment. That said, I genuinely look forward to reviewing any potential pull request (PR) should someone decide to take it on! 👍

**Comment by wroyca** [comment]
I was unable to discover a method of capturing a new tab event, which is essential if we intend to incorporate animation. This is because the subsequent tab might not necessarily be the last child, where the animation would occur in the absence of the new tab context. I'm uncertain if achieving this solely with CSS is possible, so it's probable that we'll need to delve into JS for this. Nevertheless, the latest commit hide tabs when there is only one tab present, which is already a positive step in the right direction.

**Comment by Acumane** [comment]
Big step! I'm playing with it now.
Where should I start looking/reading if I were to help implement this?

**Comment by wroyca** [comment]
> Big step! I'm playing with it now. Where should I start looking/reading if I were to help implement this?

The majority of the functionality related to tabs and their container is implemented in the tabstitlecontrol.css file, which can be found at https://github.com/wroyca/libadwaita-vscode-theme/blob/main/src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css. This is the ideal starting point for understanding and modifying this aspect. Another option is to access the developer tools through the command palette, enabling you to right-click on any element to copy its selector and locate its location using something like [ripgrep](https://github.com/BurntSushi/ripgrep).
